import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [state, setstate] = useState(null);
  useEffect(() => {
    async function func() {
      let search = await fetch(
        "http://192.168.3.10:3000/api?account_id=87683422"
      )
        .then((response) => {
          return response.json();
        })
        .then((data) => {
          return data;
        })
        .catch(() => {
          return {};
        });
     console.log(search);
      return search;
    }
    setstate(func());
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>
<input type='number'/>
      <footer className={styles.footer}></footer>
    </div>
  );
}
