import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import Image from "next/image";

export default function Home() {
  const [information, setInformation] = useState(false);
  const [value, setValue] = useState(87683422);

  async function start() {
    let search = await fetch(`http://192.168.3.10:3000/api?account_id=${value}`)
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        return data;
      })
      .catch(() => {
        return {};
      });
    console.log(search);
    await setInformation(search);
    return search;
  }

  useEffect(() => {
    console.log(information);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        type="number"
        placeholder="account id"
        onChange={(e) => {
          console.log(e.target.value);
          setValue(e.target.value);
        }}
      />
      <button onClick={start}>buscar</button>
      {information && (
        <table className="customTable">
          <thead>
            <tr>
              <th>
                <h1>{information.personaname}</h1>
              </th>
              <th>
                <img
                  src={information.avatarfull}
                  alt={information.personaname}
                  width={200}
                  height={200}
                />
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>assists</td>
              <td>{information.status_players.assists}</td>
            </tr>
            <tr>
              <td>deaths</td>
              <td>{information.status_players.deaths}</td>
            </tr>
            <tr>
              <td>denies</td>
              <td>{information.status_players.denies}</td>
            </tr>
            <tr>
              <td>gold_per_min</td>
              <td>{information.status_players.gold_per_min}</td>
            </tr>
            <tr>
              <td>hero_damage</td>
              <td>{information.status_players.hero_damage}</td>
            </tr>
            <tr>
              <td>hero_healing</td>
              <td>{information.status_players.hero_healing}</td>
            </tr>
            <tr>
              <td>kills</td>
              <td>{information.status_players.kills}</td>
            </tr>
            <tr>
              <td>last_hits</td>
              <td>{information.status_players.last_hits}</td>
            </tr>
            <tr>
              <td>net_worth</td>
              <td>{information.status_players.net_worth}</td>
            </tr>
            <tr>
              <td>tower_damage</td>
              <td>{information.status_players.tower_damage}</td>
            </tr>
            <tr>
              <td>win_rate</td>
              <td>{information.status_players.win}%</td>
            </tr>
            <tr>
              <td>xp_per_min</td>
              <td>{information.status_players.xp_per_min}</td>
            </tr>
          </tbody>
        </table>
      )}
    </>
  );
}
