import Head from "next/head";
import { useState, useEffect } from "react";
import { Math_players_single } from "../src/components/Math_data";

export default function Home() {
  const [value, setValue] = useState([{ account_id: 87683422 }]);
  const [resp, setResp] = useState([]);
  const [key, setKey] = useState([]);

  async function start() {
    const search_api = async ({ account_id, details }) => {
      let arrayValue = [];
      if (!details) {
        for (let i = 0; i < account_id.length; i++) {
          let search = fetch(
            `http://192.168.3.10:3000/api?account_id=${account_id[i].account_id}&details=${details}`
          )
            .then((response) => {
              return response.json();
            })
            .then((data) => {
              return data;
            })
            .catch(() => {
              return false;
            });
          console.log(account_id.length);
          arrayValue.push(search);
        }
      } else {
        for (let i = 0; i < account_id.length; i++) {
          let search = fetch(
            `http://192.168.3.10:3000/api?account_id=${account_id[i].account_id}&details=${details}`
          )
            .then((response) => {
              return response.json();
            })
            .then((data) => {
              return data;
            })
            .catch(() => {
              return false;
            });
          console.log(account_id.length);
          arrayValue.push(search);
          setResp(arrayValue);
        }
      }
      return Promise.all(arrayValue).then((x) => x);
    };
    //-----------------------------------
    let start_search01 = await search_api({
      account_id: value,
      details: false,
    });
    console.log("start_search01:", start_search01);
    let players_gamed01 = await Math_players_single(start_search01);
    console.log("players_gamed01:", players_gamed01);
    //------------------------------------
    let start_search02 = await (
      await search_api({
        account_id: players_gamed01,
        details: false,
      })
    )
      .filter((x) => x.error !== 500)
      .filter((x) => x.matchHistory);
    console.log("start_search02:", start_search02);
    let players_gamed02 = await Math_players_single(start_search02);
    console.log("players_gamed02:", players_gamed02);
    //-------------------------------------
    let start_search03 = await await search_api({
      account_id: players_gamed02.splice(0, 100),
      details: true,
    });
    //localStorage.setItem("data", JSON.stringify(start_search03));
    setResp(start_search03);

    console.log("resp:", resp);
    console.log("start_search03:", start_search03);

    //--------------------------------------
  }
  const onChange = (e) => {
    let k = e.target.value;
    console.log(parseInt(k));
    setValue(parseInt(k));
  };

  useEffect(() => {
    console.log("START");
    console.log(resp);

    document.addEventListener('keydown', (event) => {
      var name = event.key;
      var code = event.code;
      console.log(event)
      // Alert the key name and key code on keydown
      setKey(`Key pressed " ${name} " \r\n Key code value: ${code}`);
    }, false)
  });
  return (
    <div className="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="insert">
        <input
          className="myButton"
          type="number"
          onChange={onChange}
          value={value}
        />
        <button className="myButton" onClick={start}>
          buscar
        </button>
      </div>
      <div>{resp.map((x, i) => i)}</div>

      <div>{key}</div>

    </div>
  );
}
